import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const crevv = localFont({
  src: '../public/fonts/crevv.woff',
  variable: '--font-crevv',
  display: 'swap',
});

const ibm = localFont({
  src: '../public/fonts/IBMPlexMono-Regular.ttf',
  variable: '--font-ibm',
  display: 'swap',
});


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased ${crevv.variable} ${ibm.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
